<?php
/**
 * $Id: xoops_version.php 155 2006-02-13 14:14:05Z Michael $
 * osCommerce, Open Source E-Commerce Solutions
 * http://www.oscommerce.com
 * Copyright (c) 2003 osCommerce
 * Released under the GNU General Public License
 * adapted 2005 for xoops by FlinkUX <http://www.flinkux.de>
 * @package xosC
 * @author Michael Hammelmann <michael.hammelmann@flinkux.de>
*/

$modversion['name'] = _MI_OSC_NAME;
$modversion['version'] = "0.62";
$modversion['description'] = _MI_OSC_DESC;
$modversion['credits'] = "FlinkUX e.K.<br>Michael <michael.hammelmann@flinkux.de>";
$modversion['help'] = "No Help yet";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = "0.62";
$modversion['image'] = "images/xosclogo.gif";
$modversion['dirname'] = "osC";
$modversion['onUpdate']= 'onUpdate.php';
$modversion['onUninstall']='onUpdate.php';
// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/oscommerce.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "includes/search.inc.php";
$modversion['search']['func'] = "xosC_search";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "osc_address_book";
$modversion['tables'][1] = "osc_address_format";
$modversion['tables'][2] = "osc_banners";
$modversion['tables'][3] = "osc_banners_history";
$modversion['tables'][4] = "osc_categories";
$modversion['tables'][5] = "osc_categories_description";
$modversion['tables'][6] = "osc_configuration";
$modversion['tables'][7] = "osc_configuration_group";
$modversion['tables'][8] = "osc_counter";
$modversion['tables'][9] = "osc_counter_history";
$modversion['tables'][10] = "osc_countries";
$modversion['tables'][11] = "osc_currencies";
$modversion['tables'][12] = "osc_customers";
$modversion['tables'][13] = "osc_customers_basket";
$modversion['tables'][14] = "osc_customers_basket_attributes";
$modversion['tables'][15] = "osc_customers_info";
$modversion['tables'][16] = "osc_languages";
$modversion['tables'][17] = "osc_manufacturers";
$modversion['tables'][18] = "osc_manufacturers_info";
$modversion['tables'][19] = "osc_newsletters";
$modversion['tables'][20] = "osc_orders";
$modversion['tables'][21] = "osc_orders_products";
$modversion['tables'][22] = "osc_orders_status";
$modversion['tables'][23] = "osc_orders_status_history";
$modversion['tables'][24] = "osc_orders_products_attributes";
$modversion['tables'][25] = "osc_orders_products_download";
$modversion['tables'][26] = "osc_orders_total";
$modversion['tables'][27] = "osc_products";
$modversion['tables'][28] = "osc_products_attributes";
$modversion['tables'][29] = "osc_products_attributes_download";
$modversion['tables'][30] = "osc_products_description";
$modversion['tables'][31] = "osc_products_notifications";
$modversion['tables'][32] = "osc_products_options";
$modversion['tables'][33] = "osc_products_options_values";
$modversion['tables'][34] = "osc_products_options_values_to_products_options";
$modversion['tables'][35] = "osc_products_to_categories";
$modversion['tables'][36] = "osc_reviews";
$modversion['tables'][37] = "osc_reviews_description";
$modversion['tables'][38] = "osc_sessions";
$modversion['tables'][39] = "osc_specials";
$modversion['tables'][40] = "osc_tax_class";
$modversion['tables'][41] = "osc_tax_rates";
$modversion['tables'][42] = "osc_geo_zones";
$modversion['tables'][43] = "osc_whos_online";
$modversion['tables'][44] = "osc_zones";
$modversion['tables'][45] = "osc_zones_to_geo_zones";
$modversion['tables'][46] = "osc_coupon_email_track";
$modversion['tables'][47] = "osc_coupon_gv_customer";
$modversion['tables'][48] = "osc_coupon_gv_queue";
$modversion['tables'][49] = "osc_coupon_redeem_track";
$modversion['tables'][50] = "osc_coupons";
$modversion['tables'][51] = "osc_coupons_description";
$modversion['tables'][52] = "osc_customer_group";
$modversion['tables'][53] = "osc_edit_invoice";
$modversion['tables'][54] = "osc_distributors";
// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Blocks
$modversion['blocks'][1]['file'] = "categories.php";
$modversion['blocks'][1]['name'] = _MI_BOX_HEADING_CATEGORIES;
$modversion['blocks'][1]['description'] = _MI_BOX_HEADING_CATEGORIES_DESC;
$modversion['blocks'][1]['show_func'] = 'show_categories';
$modversion['blocks'][1]['edit_func'] = '';
$modversion['blocks'][1]['template'] = "categories.html";
$modversion['blocks'][1]['can_clone'] = false ;
$modversion['blocks'][1]['options'] = "";

$modversion['blocks'][2]['file'] = "shopping_cart.php";
$modversion['blocks'][2]['name'] = _MI_BOX_SHOPCART;
$modversion['blocks'][2]['description'] = _MI_BOX_SHOPCART_DESC;
$modversion['blocks'][2]['show_func'] = "b_shop_cart";
$modversion['blocks'][2]['template'] = 'shop_basket.html';
$modversion['blocks'][2]['can_clone'] = false ;
$modversion['blocks'][2]['options'] = "";

$modversion['blocks'][3]['file'] = "currencies.php";
$modversion['blocks'][3]['name'] = _MI_BOX_CURRENCIES;
$modversion['blocks'][3]['description'] = _MI_BOX_CURRENCIES_DESC;
$modversion['blocks'][3]['show_func'] = "b_shop_currencies";
$modversion['blocks'][3]['template'] = 'shop_currencies.html';
$modversion['blocks'][3]['can_clone'] = false ;
$modversion['blocks'][3]['options'] = "";

$modversion['blocks'][4]['file'] = "specials.php";
$modversion['blocks'][4]['name'] = _MI_BOX_SPECIALS;
$modversion['blocks'][4]['description'] = _MI_BOX_SPECIALS_DESC;
$modversion['blocks'][4]['show_func'] = "b_specials";
$modversion['blocks'][4]['template'] = 'xosc_block.html';
$modversion['blocks'][4]['can_clone'] = false ;
$modversion['blocks'][4]['options'] = "";

$modversion['blocks'][5]['file'] = "best_sellers.php";
$modversion['blocks'][5]['name'] = _MI_BOX_BEST_SELLERS;
$modversion['blocks'][5]['description'] = _MI_BOX_BEST_SELLERS_DESC;
$modversion['blocks'][5]['show_func'] = "b_best_sellers";
$modversion['blocks'][5]['template'] = 'xosc_block.html';
$modversion['blocks'][5]['can_clone'] = false ;
$modversion['blocks'][5]['options'] = "";

$modversion['blocks'][6]['file'] = "manufacturers.php";
$modversion['blocks'][6]['name'] = _MI_BOX_MANUFACTURERS;
$modversion['blocks'][6]['description'] = _MI_BOX_MANUFACTURERS_DESC;
$modversion['blocks'][6]['show_func'] = "show_manufacturers";
$modversion['blocks'][6]['template'] = 'xosc_block.html';
$modversion['blocks'][6]['can_clone'] = false ;
$modversion['blocks'][6]['options'] = "";


$modversion['blocks'][7]['file'] = "search.php";
$modversion['blocks'][7]['name'] = _MI_BOX_SEARCH;
$modversion['blocks'][7]['description'] = _MI_BOX_SEARCH_DESC;
$modversion['blocks'][7]['show_func'] = "show_search";
$modversion['blocks'][7]['template'] = 'xosc_block.html';
$modversion['blocks'][7]['can_clone'] = false ;
$modversion['blocks'][7]['options'] = "";

// Templates
$modversion['templates'][1]['file'] = 'header.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'form_check.js.html';
$modversion['templates'][2]['description'] = '';
$modversion['templates'][3]['file'] = 'address_book_details.html';
$modversion['templates'][3]['description'] = '';
$modversion['templates'][4]['file'] = 'checkout_shipping.js';
$modversion['templates'][4]['description'] = '';

$modversion['templates'][5]['file'] = 'login.html';
$modversion['templates'][5]['description'] = '';
$modversion['templates'][6]['file'] = 'create_account_success.html';
$modversion['templates'][6]['description'] = '';
$modversion['templates'][7]['file'] = 'index.html';
$modversion['templates'][7]['description'] = '';
$modversion['templates'][8]['file'] = 'upcoming_products.html';
$modversion['templates'][8]['description'] = '';
$modversion['templates'][9]['file'] = 'checkout_confirmation.html';
$modversion['templates'][9]['description'] = '';
$modversion['templates'][10]['file'] = 'checkout_payment.html';
$modversion['templates'][10]['description'] = '';
$modversion['templates'][11]['file'] = 'product_info.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][12]['file'] = 'account.html';
$modversion['templates'][12]['description'] = '';
$modversion['templates'][13]['file'] = 'account_edit.html';
$modversion['templates'][13]['description'] = '';
$modversion['templates'][14]['file'] = 'account_history.html';
$modversion['templates'][14]['description'] = '';
$modversion['templates'][15]['file'] = 'account_newsletters.html';
$modversion['templates'][15]['description'] = '';
$modversion['templates'][16]['file'] = 'account_notifications.html';
$modversion['templates'][16]['description'] = '';
$modversion['templates'][17]['file'] = 'account_password.html';
$modversion['templates'][17]['description'] = '';
$modversion['templates'][18]['file'] = 'address_book.html';
$modversion['templates'][18]['description'] = '';
$modversion['templates'][19]['file'] = 'product_listing.html';
$modversion['templates'][19]['description'] = '';
$modversion['templates'][20]['file'] = 'logoff.html';
$modversion['templates'][20]['description'] = '';
$modversion['templates'][21]['file'] = 'address_book_process.html';
$modversion['templates'][21]['description'] = '';
$modversion['templates'][22]['file'] = 'create_account.html';
$modversion['templates'][22]['description'] = '';
$modversion['templates'][23]['file'] = 'downloads.html';
$modversion['templates'][23]['description'] = '';
$modversion['templates'][24]['file'] = 'shopping_cart.html';
$modversion['templates'][24]['description'] = '';
$modversion['templates'][25]['file'] = 'checkout_success.html';
$modversion['templates'][25]['description'] = '';
$modversion['templates'][26]['file'] = 'checkout_new_address.html';
$modversion['templates'][26]['description'] = '';
$modversion['templates'][27]['file'] = 'checkout_payment_address.html';
$modversion['templates'][27]['description'] = '';
$modversion['templates'][28]['file'] = 'product_reviews.html';
$modversion['templates'][28]['description'] = '';
$modversion['templates'][29]['file'] = 'product_reviews_write.html';
$modversion['templates'][29]['description'] = '';
$modversion['templates'][30]['file'] = 'password_forgotten.html';
$modversion['templates'][30]['description'] = '';
$modversion['templates'][31]['file'] = 'account_history_info.html';
$modversion['templates'][31]['description'] = '';
$modversion['templates'][32]['file'] = 'checkout_shipping_address.html';
$modversion['templates'][32]['description'] = '';
$modversion['templates'][33]['file'] = 'products_new.html';
$modversion['templates'][33]['description'] = '';
$modversion['templates'][34]['file'] = 'product_reviews_info.html';
$modversion['templates'][34]['description'] = '';
$modversion['templates'][35]['file'] = 'shipping_handling.html';
$modversion['templates'][35]['description'] = '';
$modversion['templates'][36]['file'] = 'terms_of_agreement.html';
$modversion['templates'][36]['description'] = '';
$modversion['templates'][37]['file'] = 'terms_of_revoke.html';
$modversion['templates'][37]['description'] = '';
$modversion['templates'][38]['file'] = 'gv_redeem.html';
$modversion['templates'][38]['description'] = '';
$modversion['templates'][39]['file'] = 'gv_faq.html';
$modversion['templates'][39]['description'] = '';
$modversion['templates'][40]['file'] = 'gv_send.html';
$modversion['templates'][40]['description'] = '';
$modversion['templates'][41]['file'] = 'checkout_shipping.html';
$modversion['templates'][41]['description'] = '';
$modversion['templates'][42]['file'] = 'advanced_search.html';
$modversion['templates'][42]['description'] = '';
$modversion['templates'][43]['file'] = 'advanced_search_result.html';
$modversion['templates'][43]['description'] = '';

// Menu
$modversion['hasMain'] = 1;
?>