<?php
// $Id: xoops_version.php,v 1.2 Date: 06/01/2003, Author: Catzwolf Exp $

$modversion['name'] = _MI_WFS_NAME;
$modversion['version'] = 1.01;
$modversion['description'] = _MI_WFS_DESC;
$modversion['author'] = "Catzwolf";
$modversion['credits'] = "Catzwolf";
//
$modversion['help'] = "wfsection.html";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 1;
$modversion['image'] = "images/wfs_slogo.gif";
$modversion['dirname'] = "wfsection";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/wfsection.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
//$modversion['tables'][0] = "wfs_comments";
$modversion['tables'][1] = "wfs_article";
$modversion['tables'][2] = "wfs_category";
$modversion['tables'][3] = "wfs_files";
$modversion['tables'][4] = "wfs_config";
$modversion['tables'][5] = "wfs_broken";
$modversion['tables'][6] = "wfs_votedata";
// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Blocks

$modversion['blocks'][1]['file'] = "wfs_artmenu.php";
$modversion['blocks'][1]['name'] = _MI_WFS_BNAME_ARTMENU;
$modversion['blocks'][1]['description'] = "Shows Article menu";
$modversion['blocks'][1]['show_func'] = "b_wfs_artmenu";
$modversion['blocks'][1]['template'] = 'wfs_block.artmenu.html';

$modversion['blocks'][2]['file'] = "wfs_menu.php";
$modversion['blocks'][2]['name'] = _MI_WFS_BNAME_MENU;
$modversion['blocks'][2]['description'] = "Shows category menu";
$modversion['blocks'][2]['show_func'] = "b_wfs_menu";
$modversion['blocks'][2]['template'] = 'wfs_block.menu.html';

$modversion['blocks'][3]['file'] = "wfs_topics.php";
$modversion['blocks'][3]['name'] = _MI_WFS_TOPICS;
$modversion['blocks'][3]['description'] = "WFS Category";
$modversion['blocks'][3]['show_func'] = "b_wfs_topics_show";
$modversion['blocks'][3]['template'] = 'wfs_block_topics.html';

$modversion['blocks'][4]['file'] = "wfs_bigstory.php";
$modversion['blocks'][4]['name'] = _MI_WFS_BNAME3;
$modversion['blocks'][4]['description'] = "Shows most read story of the day";
$modversion['blocks'][4]['show_func'] = "b_wfs_bigstory_show";
$modversion['blocks'][4]['template'] = 'wfs_block_bigstory.html';

$modversion['blocks'][5]['file'] = "wfs_top.php";
$modversion['blocks'][5]['name'] = _MI_WFS_BNAME4;
$modversion['blocks'][5]['description'] = "Shows top read news articles";
$modversion['blocks'][5]['show_func'] = "b_wfs_top_show";
$modversion['blocks'][5]['edit_func'] = "b_wfs_top_edit";
$modversion['blocks'][5]['options'] = "counter|10|25";
$modversion['blocks'][5]['template'] = 'wfs_block_top.html';

$modversion['blocks'][6]['file'] = "wfs_new.php";
$modversion['blocks'][6]['name'] = _MI_WFS_BNAME5;
$modversion['blocks'][6]['description'] = "Shows recent articles";
$modversion['blocks'][6]['show_func'] = "b_wfs_new_show";
$modversion['blocks'][6]['edit_func'] = "b_wfs_new_edit";
$modversion['blocks'][6]['options'] = "published|10|25";
$modversion['blocks'][6]['template'] = 'wfs_block_new.html';

$modversion['blocks'][7]['file'] = "wfs_newdown.php";
$modversion['blocks'][7]['name'] = _MI_WFS_BNAME6;
$modversion['blocks'][7]['description'] = "Shows article downloads";
$modversion['blocks'][7]['show_func'] = "b_wfs_down_show";
$modversion['blocks'][7]['edit_func'] = "b_wfs_down_edit";
$modversion['blocks'][7]['options'] = "date|10|25";
$modversion['blocks'][7]['template'] = 'wfs_block_newdown.html';
// Menu
$modversion['hasMain'] = 1;
$modversion['sub'][1]['name'] = _MI_WFS_SUBMIT;
$modversion['sub'][1]['url'] = "submit.php";
$modversion['sub'][2]['name'] = _MI_WFS_POPULAR;
$modversion['sub'][2]['url'] = "topten.php?counter=1";
$modversion['sub'][3]['name'] = _MI_WFS_RATEFILE;
$modversion['sub'][3]['url'] = "topten.php?rate=1";

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "include/search.inc.php";
$modversion['search']['func'] = "wfsection_search";

// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['pageName'] = 'article.php';
$modversion['comments']['itemName'] = 'articleid';
// Comment callback functions
$modversion['comments']['callbackFile'] = 'include/comment_functions.php';
$modversion['comments']['callback']['approve'] = 'wfsection_com_approve';
$modversion['comments']['callback']['update'] = 'wfsection_com_update';

// Templates
$modversion['templates'][1]['file'] = 'wfsection_article.html';
$modversion['templates'][1]['description'] = 'Display article';
$modversion['templates'][2]['file'] = 'wfsection_topten.html';
$modversion['templates'][2]['description'] = '';
$modversion['templates'][3]['file'] = 'wfsection_htmlart.html';
$modversion['templates'][3]['description'] = 'Display html article';
?>
