<?php
// $Id: xoops_version.php,v 1.7 2006/05/28 09:20:19 ohwada Exp $

// 2006-05-28 K.OHWADA
// v1.12

// 2006-03-20 K.OHWADA
// v1.11

// 2005-11-20 K.OHWADA
// v1.10

// 2005-09-10 K.OHWADA
// v1.09

// 2005-06-20 K.OHWADA
// v1.08

// 2004/07/14 K.OHWADA
// v1.07

// 2004/03/27 K.OHWADA
// v1.06

// 2004/02/28 K.OHWADA
// v1.05

// 2004/01/25 K.OHWADA
// v1.04
// permit the auther to modify article

// 2003/11/21 K.OHWADA
// v1.03
// bug fix
//   search don't work

// 2003/10/11 K.OHWADA
// v1.02
// rename module wfsection to xfsection 

$modversion['name'] = _MI_XFS_NAME;	// wfs -> xfs
$modversion['version'] = 1.12;
$modversion['description'] = _MI_XFS_DESC;	// wfs -> xfs
$modversion['author'] = "Catzwolf,Ohwada";	// add Ohwada
$modversion['credits'] = "Catzwolf,Ohwada";	// add Ohwada
//
$modversion['help'] = "wfsection.html";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 1;
$modversion['image'] = "images/xfs_slogo.gif";	// wfs -> xfs
$modversion['dirname'] = "xfsection";	// wfs -> xfs

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/xfsection.sql";	// wfs -> xfs
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
//$modversion['tables'][0] = "wfs_comments";
$modversion['tables'][1] = "xfs_article";	// wfs -> xfs
$modversion['tables'][2] = "xfs_category";
$modversion['tables'][3] = "xfs_files";
$modversion['tables'][4] = "xfs_config";
$modversion['tables'][5] = "xfs_broken";
$modversion['tables'][6] = "xfs_votedata";
// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Blocks
$modversion['blocks'][1]['file'] = "xfs_artmenu.php";	// wfs -> xfs
$modversion['blocks'][1]['name'] = _MI_XFS_BNAME_ARTMENU;
$modversion['blocks'][1]['description'] = "Shows Article menu";
$modversion['blocks'][1]['show_func'] = "b_xfs_artmenu";
$modversion['blocks'][1]['template'] = 'xfs_block.artmenu.html';

$modversion['blocks'][2]['file'] = "xfs_menu.php";	// wfs -> xfs
$modversion['blocks'][2]['name'] = _MI_XFS_BNAME_MENU;
$modversion['blocks'][2]['description'] = "Shows category menu";
$modversion['blocks'][2]['show_func'] = "b_xfs_menu";
$modversion['blocks'][2]['template'] = 'xfs_block.menu.html';

$modversion['blocks'][3]['file'] = "xfs_topics.php";	// wfs -> xfs
$modversion['blocks'][3]['name'] = _MI_XFS_TOPICS;
$modversion['blocks'][3]['description'] = "WFS Category";
$modversion['blocks'][3]['show_func'] = "b_xfs_topics_show";
$modversion['blocks'][3]['template'] = 'xfs_block_topics.html';

$modversion['blocks'][4]['file'] = "xfs_bigstory.php";	// wfs -> xfs
$modversion['blocks'][4]['name'] = _MI_XFS_BNAME3;
$modversion['blocks'][4]['description'] = "Shows most read story of the day";
$modversion['blocks'][4]['show_func'] = "b_xfs_bigstory_show";
$modversion['blocks'][4]['template'] = 'xfs_block_bigstory.html';

$modversion['blocks'][5]['file'] = "xfs_top.php";	// wfs -> xfs
$modversion['blocks'][5]['name'] = _MI_XFS_BNAME4;
$modversion['blocks'][5]['description'] = "Shows top read news articles";
$modversion['blocks'][5]['show_func'] = "b_xfs_top_show";
$modversion['blocks'][5]['edit_func'] = "b_xfs_top_edit";
$modversion['blocks'][5]['options'] = "counter|10|25";
$modversion['blocks'][5]['template'] = 'xfs_block_top.html';

$modversion['blocks'][6]['file'] = "xfs_new.php";	// wfs -> xfs
$modversion['blocks'][6]['name'] = _MI_XFS_BNAME5;
$modversion['blocks'][6]['description'] = "Shows recent articles";
$modversion['blocks'][6]['show_func'] = "b_xfs_new_show";
$modversion['blocks'][6]['edit_func'] = "b_xfs_new_edit";
$modversion['blocks'][6]['options'] = "published|10|25";
$modversion['blocks'][6]['template'] = 'xfs_block_new.html';

$modversion['blocks'][7]['file'] = "xfs_newdown.php";	// wfs -> xfs
$modversion['blocks'][7]['name'] = _MI_XFS_BNAME6;
$modversion['blocks'][7]['description'] = "Shows article downloads";
$modversion['blocks'][7]['show_func'] = "b_xfs_down_show";
$modversion['blocks'][7]['edit_func'] = "b_xfs_down_edit";
$modversion['blocks'][7]['options'] = "date|10|25";
$modversion['blocks'][7]['template'] = 'xfs_block_newdown.html';
// Menu
$modversion['hasMain'] = 1;
$modversion['sub'][1]['name'] = _MI_XFS_SUBMIT;	// wfs -> xfs
$modversion['sub'][1]['url'] = "submit.php";
$modversion['sub'][2]['name'] = _MI_XFS_POPULAR;
$modversion['sub'][2]['url'] = "topten.php?counter=1";
$modversion['sub'][3]['name'] = _MI_XFS_RATEFILE;
$modversion['sub'][3]['url'] = "topten.php?rate=1";

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "include/search.inc.php";

// bug fix : search don't work
//$modversion['search']['func'] = "wfsection_search";
$modversion['search']['func'] = "xfsection_search";

// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['pageName'] = 'article.php';
$modversion['comments']['itemName'] = 'articleid';
// Comment callback functions
$modversion['comments']['callbackFile'] = 'include/comment_functions.php';
$modversion['comments']['callback']['approve'] = 'wfsection_com_approve';
$modversion['comments']['callback']['update'] = 'wfsection_com_update';

// Templates
$modversion['templates'][1]['file'] = "xfsection_article.html";	// wfs -> xfs
$modversion['templates'][1]['description'] = 'Display article';
$modversion['templates'][2]['file'] = "xfsection_topten.html";
$modversion['templates'][2]['description'] = '';
$modversion['templates'][3]['file'] = "xfsection_htmlart.html";
$modversion['templates'][3]['description'] = 'Display html article';

?>