<?php 
$TAleatorio= "1";
$TBloque= "1";
$TMCatalogos= "";
$TAnchoBloque= "150";
$TAltoBloque= "100";
$TAnchoImagenes= "150";
$TAltoImagenes= "100";
$TFotosAncho= "4";
$TFotosAlto= "3";
$TEnviarFicheros= "1";
$TEnviarComentarios= "1";
$TEnviarVotaciones= "1";
$TEnviarEnlaces= "1";
$TNecesarioRegistrar= "";
$TInicioDescargas= "";
$TFinDescargas= "";
$TInicioEnlaces= "";
$TFinEnlaces= "";
$TAnterior= "<img src=\"icons/previous.gif\">";
$TSiguiente= "<img src=\"icons/next.gif\">";
$TInicioEncabezado= "<CENTER><img src=\"icons/leftside.gif\">";
$TFinEncabezado= "<img src=\"icons/rightside.gif\"></CENTER>";
$TInicioPie= "";
$TFinPie= "";
$TInicioEncabezadoComentario= "";
$TFinEncabezadoComentario= "";
$TInicioComentario= "";
$TFinComentario= "";
$TBloquearImagenesSubidas= "";
$TBloquearComentarios= "";
$TInicioFoto= "";
$TFinFoto= "";
$TInicioFotoGrande= "";
$TFinFotoGrande= "";
$TInicioMarcoFoto= "";
$TFinMarcoFoto= "";
$TVerVisitas= "1";
$TVerFecha= "1";
$TTemaCargado= "xgallery";
$TFotoDescripcion= "";
$TUsarGraficoEnNombre= "1";
$TAleatorioListado= "1";
$TPermitirImprimir= "";
$TPermitirMail= "";
$TNombreFotoCarpeta= "galiciaverano2001i.gif";
$TNombreFotoCarpetaSuperior= "galiciaverano2001.gif";
$TBordeImagenIzquierda= "frame_small_left.gif";
$TBordeImagenDerecha= "frame_small_right.gif";
$TBordeImagenArriba= "frame_small_top.gif";
$TBordeImagenAbajo= "frame_small_bottom.gif";
$TUsarBordes= "1";
$TBordesTema= "1";
$TBordeImagenPequenoIzquierda= "frame_small_left.gif";
$TBordeImagenPequenoDerecha= "frame_small_right.gif";
$TBordeImagenPequenoArriba= "frame_small_top.gif";
$TBordeImagenPequenoAbajo= "frame_small_bottom.gif";
$TBordeImagenGrandeIzquierdaArriba= "1";
$TBordeImagenGrandeIzquierdaCentro= "2";
$TBordeImagenGrandeIzquierdaAbajo= "3";
$TBordeImagenGrandeCentroArriba= "4";
$TBordeImagenGrandeCentroAbajo= "5";
$TBordeImagenGrandeDerechaArriba= "6";
$TBordeImagenGrandeDerechaCentro= "7";
$TBordeImagenGrandeDerechaAbajo= "8";
?>
