<?php
// $Id: version.php,v 1.10 2003/03/11 20:27:35 okazu Exp $
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //
$modversion['name'] = "Zen Cart Xoops";
$modversion['version'] = "0.1";
$modversion['author'] = 'http://dev.imaginacolombia.com';
$modversion['description'] = "Zen Cart Xoops Integration";
$modversion['credits'] = "http://dev.imaginacolombia.com";
$modversion['help'] = "news.html";
$modversion['license'] = "GPL";
$modversion['official'] = 1;
$modversion['image'] = "images/admin.gif";
$modversion['dirname'] = "shop";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/shop.sql";

				$modversion['tables'][0] = "zcaddress_book";
				$modversion['tables'][1] = "zcaddress_format";
                $modversion['tables'][2] = "zcadmin";
                $modversion['tables'][3] = "zcadmin_activity_log";
                $modversion['tables'][4] = "zcauthorizenet";
                $modversion['tables'][5] = "zcbanners";
                $modversion['tables'][6] = "zcbanners_history";

                $modversion['tables'][7] = "zccategories";
                $modversion['tables'][8] = "zccategories_description";
                $modversion['tables'][9] = "zcconfiguration";
                $modversion['tables'][10] = "zcconfiguration_group";
                $modversion['tables'][11] = "zccounter";
                $modversion['tables'][12] = "zccounter_history";

                $modversion['tables'][13] = "zccountries";
                $modversion['tables'][14] = "zccoupon_email_track";
                $modversion['tables'][15] = "zccoupon_gv_customer";
                $modversion['tables'][16] = "zccoupon_gv_queue";
                $modversion['tables'][17] = "zccoupon_redeem_track";
                $modversion['tables'][18] = "zccoupon_restrict";

                $modversion['tables'][19] = "zccoupons";
                $modversion['tables'][20] = "zccoupons_description";
                $modversion['tables'][21] = "zccurrencies";
                $modversion['tables'][22] = "zccustomers";
                $modversion['tables'][23] = "zccustomers_basket";
                $modversion['tables'][24] = "zccustomers_basket_attributes";

                $modversion['tables'][25] = "zccustomers_info";
                $modversion['tables'][26] = "zccustomers_wishlist";
                $modversion['tables'][27] = "zcdb_cache";
                $modversion['tables'][28] = "zcemail_archive";
                $modversion['tables'][29] = "zcfeatured";
                $modversion['tables'][30] = "zcfiles_uploaded";

                $modversion['tables'][31] = "zcgeo_zones";
                $modversion['tables'][32] = "zcget_terms_to_filter";
                $modversion['tables'][33] = "zcgroup_pricing";
                $modversion['tables'][34] = "zclanguages";
                $modversion['tables'][35] = "zclayout_boxes";
                $modversion['tables'][36] = "zcmanufacturers";

                $modversion['tables'][37] = "zcmanufacturers_info";
                $modversion['tables'][38] = "zcmedia_clips";
                $modversion['tables'][39] = "zcmedia_manager";
                $modversion['tables'][40] = "zcmedia_to_products";
                $modversion['tables'][41] = "zcmedia_types";
                $modversion['tables'][42] = "zcmeta_tags_products_description";

                $modversion['tables'][43] = "zcmusic_genre";
                $modversion['tables'][44] = "zcnewsletters";
                $modversion['tables'][45] = "zcorders";
                $modversion['tables'][46] = "zcorders_products";
                $modversion['tables'][47] = "zcorders_products_attributes";
                $modversion['tables'][48] = "zcorders_products_download";

                $modversion['tables'][49] = "zcorders_status";
                $modversion['tables'][50] = "zcorders_status_history";
                $modversion['tables'][51] = "zcorders_total";
                $modversion['tables'][52] = "zcpaypal";
                $modversion['tables'][53] = "zcpaypal_payment_status";
                $modversion['tables'][54] = "zcpaypal_payment_status_history";

                $modversion['tables'][55] = "zcpaypal_session";
                $modversion['tables'][56] = "zcproduct_music_extra";
                $modversion['tables'][57] = "zcproduct_type_layout";
                $modversion['tables'][58] = "zcproduct_types";
                $modversion['tables'][59] = "zcproduct_types_to_category";
                $modversion['tables'][60] = "zcproducts";

                $modversion['tables'][61] = "zcproducts_attributes";
                $modversion['tables'][62] = "zcproducts_attributes_download";
                $modversion['tables'][63] = "zcproducts_description";
                $modversion['tables'][64] = "zcproducts_discount_quantity";
                $modversion['tables'][65] = "zcproducts_notifications";
                $modversion['tables'][66] = "zcproducts_options";

                $modversion['tables'][67] = "zcproducts_options_types";
                $modversion['tables'][68] = "zcproducts_options_values";
                $modversion['tables'][69] = "zcproducts_options_values_to_products_options";
                $modversion['tables'][70] = "zcproducts_to_categories";
                $modversion['tables'][71] = "zcproject_version";
                $modversion['tables'][72] = "zcproject_version_history";

                $modversion['tables'][73] = "zcquery_builder";
                $modversion['tables'][74] = "zcrecord_artists";
                $modversion['tables'][75] = "zcrecord_artists_info";
                $modversion['tables'][76] = "zcrecord_company";
                $modversion['tables'][77] = "zcrecord_company_info";
                $modversion['tables'][78] = "zcreviews";

                $modversion['tables'][79] = "zcreviews_description";
                $modversion['tables'][80] = "zcsalemaker_sales";
                $modversion['tables'][81] = "zcsessions";
                $modversion['tables'][82] = "zcspecials";
                $modversion['tables'][83] = "zctax_class";
                $modversion['tables'][84] = "zctax_rates";

                $modversion['tables'][85] = "zctemplate_select";
                $modversion['tables'][86] = "zcupgrade_exceptions";
                $modversion['tables'][87] = "zcwhos_online";
                $modversion['tables'][88] = "zczones";
                $modversion['tables'][89] = "zczones_to_geo_zones";

// Install things
// $modversion['onInstall'] = "includes/xoopsinstall.php";

// Admin things
$modversion['hasAdmin']   = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu']  = "admin/menu.php";

$modversion['blocks'][1]['file'] = "blocks.php";
$modversion['blocks'][1]['name'] = "Zen Cart Blocks";
$modversion['blocks'][1]['description'] = "Zen Cart Blocks";
$modversion['blocks'][1]['show_func'] = "b_shop_blocks";
$modversion['blocks'][1]['edit_func'] = 'b_shop_blocks_edit';
$modversion['blocks'][1]['template'] = 'shop_standard.html';
$modversion['blocks'][1]['options'] = "categories";

$modversion['hasMain'] = 1;
$modversion['sub'][1]['name'] = "Home";
$modversion['sub'][1]['url'] = "index.php";

// Search
$modversion['hasSearch'] = 0;

// Comments
$modversion['hasComments'] = 0;
?>