# osCommerce, Open Source E-Commerce Solutions
# http://www.oscommerce.com
#
# Ver 2.0

insert into osc_configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, last_modified, date_added, use_function, set_function) values ('Enable moneybookers Module', 'MODULE_PAYMENT_MONEYBOOKERS_STATUS', 'False', 'Do you want to accept moneybookers payments?', '6', '3', NULL, '2003-01-20 12:19:37', NULL, 'tep_cfg_select_option(array(\'True\', \'False\'),');
insert into osc_configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, last_modified, date_added, use_function, set_function) values ('E-Mail Address', 'MODULE_PAYMENT_MONEYBOOKERS_ID', '', 'The eMail address to use for the moneybookers service', '6', '4', NULL, '2003-01-20 12:19:37', NULL, NULL);
insert into osc_configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, last_modified, date_added, use_function, set_function) values ('Referral ID', 'MODULE_PAYMENT_MONEYBOOKERS_REFID', '', 'Your personal Referral ID from moneybookers.com', '6', '5', NULL, '2003-01-20 12:19:37', NULL, '');
insert into osc_configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, last_modified, date_added, use_function, set_function) values ('Transaction Language', 'MODULE_PAYMENT_MONEYBOOKERS_LANGUAGE', 'EN', 'The language for the payment transactions', '6', '6', NULL, '2003-01-20 12:19:37', NULL, 'tep_cfg_select_option(array(\'Selected Language\',\'DE\', \'EN\', \'FR\', \'ES\'),');
insert into osc_configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, last_modified, date_added, use_function, set_function) values ('Transaction Currency', 'MODULE_PAYMENT_MONEYBOOKERS_CURRENCY', 'EUR', 'The currency to use for credit card transactions', '6', '7', NULL, '2003-01-20 12:19:37', NULL, 'tep_cfg_select_option(array(\'Selected Currency\',\'EUR\', \'USD\', \'GBP\', \'HKD\', \'SGD\', \'JPY\', \'CAD\', \'AUD\', \'CHF\', \'DKK\', \'SEK\', \'NOK\', \'ILS\', \'MYR\', \'NZD\', \'TWD\', \'THB\', \'CZK\', \'HUF\', \'SKK\', \'ISK\', \'INR\'),');
insert into osc_configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, date_added) values ('Sort order of display.', 'MODULE_PAYMENT_MONEYBOOKERS_SORT_ORDER', '0', 'Sort order of display. Lowest is displayed first.', '6', '0', '2003-01-20 12:19:37');



create table osc_countries (
  countries_id int(11) not null auto_increment,
  countries_name varchar(64) not null ,
  countries_iso_code_2 char(2) not null ,
  countries_iso_code_3 char(3) not null ,
  countries_moneybookers char(3) ,
  address_format_id int(11) default '0' not null ,
  PRIMARY KEY (countries_id),
  KEY IDX_COUNTRIES_NAME (countries_name)
);

insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('1', 'Afghanistan', 'AF', 'AFG', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('2', 'Albania', 'AL', 'ALB', 'ALB', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('3', 'Algeria', 'DZ', 'DZA', 'ALG', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('4', 'American Samoa', 'AS', 'ASM', 'AME', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('5', 'Andorra', 'AD', 'AND', 'AND', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('6', 'Angola', 'AO', 'AGO', 'AGL', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('7', 'Anguilla', 'AI', 'AIA', 'ANG', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('8', 'Antarctica', 'AQ', 'ATA', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('9', 'Antigua and Barbuda', 'AG', 'ATG', 'ANT', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('10', 'Argentina', 'AR', 'ARG', 'ARG', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('11', 'Armenia', 'AM', 'ARM', 'ARM', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('12', 'Aruba', 'AW', 'ABW', 'ARU', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('13', 'Australia', 'AU', 'AUS', 'AUS', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('14', 'Austria', 'AT', 'AUT', 'AUT', '5');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('15', 'Azerbaijan', 'AZ', 'AZE', 'AZE', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('16', 'Bahamas', 'BS', 'BHS', 'BMS', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('17', 'Bahrain', 'BH', 'BHR', 'BAH', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('18', 'Bangladesh', 'BD', 'BGD', 'BAN', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('19', 'Barbados', 'BB', 'BRB', 'BAR', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('20', 'Belarus', 'BY', 'BLR', 'BLR', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('21', 'Belgium', 'BE', 'BEL', 'BGM', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('22', 'Belize', 'BZ', 'BLZ', 'BEL', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('23', 'Benin', 'BJ', 'BEN', 'BEN', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('24', 'Bermuda', 'BM', 'BMU', 'BER', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('25', 'Bhutan', 'BT', 'BTN', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('26', 'Bolivia', 'BO', 'BOL', 'BOL', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('27', 'Bosnia and Herzegowina', 'BA', 'BIH', 'BOS', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('28', 'Botswana', 'BW', 'BWA', 'BOT', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('29', 'Bouvet Island', 'BV', 'BVT', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('30', 'Brazil', 'BR', 'BRA', 'BRA', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('31', 'British Indian Ocean Territory', 'IO', 'IOT', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('32', 'Brunei Darussalam', 'BN', 'BRN', 'BRU', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('33', 'Bulgaria', 'BG', 'BGR', 'BUL', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('34', 'Burkina Faso', 'BF', 'BFA', 'BKF', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('35', 'Burundi', 'BI', 'BDI', 'BUR', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('36', 'Cambodia', 'KH', 'KHM', 'CAM', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('37', 'Cameroon', 'CM', 'CMR', 'CMR', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('38', 'Canada', 'CA', 'CAN', 'CAN', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('39', 'Cape Verde', 'CV', 'CPV', 'CAP', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('40', 'Cayman Islands', 'KY', 'CYM', 'CAY', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('41', 'Central African Republic', 'CF', 'CAF', 'CEN', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('42', 'Chad', 'TD', 'TCD', 'CHA', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('43', 'Chile', 'CL', 'CHL', 'CHL', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('44', 'China', 'CN', 'CHN', 'CHN', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('45', 'Christmas Island', 'CX', 'CXR', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('46', 'Cocos (Keeling) Islands', 'CC', 'CCK', 'COO', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('47', 'Colombia', 'CO', 'COL', 'COL', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('48', 'Comoros', 'KM', 'COM', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('49', 'Congo', 'CG', 'COG', 'CON', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('50', 'Cook Islands', 'CK', 'COK', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('51', 'Costa Rica', 'CR', 'CRI', 'COS', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('52', 'Cote D\'Ivoire', 'CI', 'CIV', 'COT', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('53', 'Croatia', 'HR', 'HRV', 'CRO', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('54', 'Cuba', 'CU', 'CUB', 'CUB', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('55', 'Cyprus', 'CY', 'CYP', 'CYP', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('56', 'Czech Republic', 'CZ', 'CZE', 'CZE', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('57', 'Denmark', 'DK', 'DNK', 'DEN', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('58', 'Djibouti', 'DJ', 'DJI', 'DJI', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('59', 'Dominica', 'DM', 'DMA', 'DOM', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('60', 'Dominican Republic', 'DO', 'DOM', 'DRP', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('61', 'East Timor', 'TP', 'TMP', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('62', 'Ecuador', 'EC', 'ECU', 'ECU', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('63', 'Egypt', 'EG', 'EGY', 'EGY', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('64', 'El Salvador', 'SV', 'SLV', 'EL_', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('65', 'Equatorial Guinea', 'GQ', 'GNQ', 'EQU', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('66', 'Eritrea', 'ER', 'ERI', 'ERI', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('67', 'Estonia', 'EE', 'EST', 'EST', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('68', 'Ethiopia', 'ET', 'ETH', 'ETH', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('69', 'Falkland Islands (Malvinas)', 'FK', 'FLK', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('70', 'Faroe Islands', 'FO', 'FRO', 'FAR', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('71', 'Fiji', 'FJ', 'FJI', 'FIJ', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('72', 'Finland', 'FI', 'FIN', 'FIN', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('73', 'France', 'FR', 'FRA', 'FRA', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('74', 'France, Metropolitan', 'FX', 'FXX', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('75', 'French Guiana', 'GF', 'GUF', 'FRE', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('76', 'French Polynesia', 'PF', 'PYF', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('77', 'French Southern Territories', 'TF', 'ATF', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('78', 'Gabon', 'GA', 'GAB', 'GAB', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('79', 'Gambia', 'GM', 'GMB', 'GAM', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('80', 'Georgia', 'GE', 'GEO', 'GEO', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('81', 'Germany', 'DE', 'DEU', 'GER', '5');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('82', 'Ghana', 'GH', 'GHA', 'GHA', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('83', 'Gibraltar', 'GI', 'GIB', 'GIB', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('84', 'Greece', 'GR', 'GRC', 'GRC', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('85', 'Greenland', 'GL', 'GRL', 'GRL', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('86', 'Grenada', 'GD', 'GRD', 'GRE', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('87', 'Guadeloupe', 'GP', 'GLP', 'GDL', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('88', 'Guam', 'GU', 'GUM', 'GUM', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('89', 'Guatemala', 'GT', 'GTM', 'GUA', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('90', 'Guinea', 'GN', 'GIN', 'GUI', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('91', 'Guinea-bissau', 'GW', 'GNB', 'GBS', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('92', 'Guyana', 'GY', 'GUY', 'GUY', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('93', 'Haiti', 'HT', 'HTI', 'HAI', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('94', 'Heard and Mc Donald Islands', 'HM', 'HMD', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('95', 'Honduras', 'HN', 'HND', 'HON', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('96', 'Hong Kong', 'HK', 'HKG', 'HKG', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('97', 'Hungary', 'HU', 'HUN', 'HUN', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('98', 'Iceland', 'IS', 'ISL', 'ICE', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('99', 'India', 'IN', 'IND', 'IND', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('100', 'Indonesia', 'ID', 'IDN', 'IDS', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('101', 'Iran (Islamic Republic of)', 'IR', 'IRN', 'IRN', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('102', 'Iraq', 'IQ', 'IRQ', 'IRA', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('103', 'Ireland', 'IE', 'IRL', 'IRE', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('104', 'Israel', 'IL', 'ISR', 'ISR', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('105', 'Italy', 'IT', 'ITA', 'ITA', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('106', 'Jamaica', 'JM', 'JAM', 'JAM', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('107', 'Japan', 'JP', 'JPN', 'JAP', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('108', 'Jordan', 'JO', 'JOR', 'JOR', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('109', 'Kazakhstan', 'KZ', 'KAZ', 'KAZ', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('110', 'Kenya', 'KE', 'KEN', 'KEN', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('111', 'Kiribati', 'KI', 'KIR', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('112', 'Korea, Democratic People\'s Republic of', 'KP', 'PRK', 'SKO', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('113', 'Korea, Republic of', 'KR', 'KOR', 'KOR', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('114', 'Kuwait', 'KW', 'KWT', 'KUW', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('115', 'Kyrgyzstan', 'KG', 'KGZ', 'KYR', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('116', 'Lao People\'s Democratic Republic', 'LA', 'LAO', 'LAO', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('117', 'Latvia', 'LV', 'LVA', 'LAT', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('118', 'Lebanon', 'LB', 'LBN', 'LEB', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('119', 'Lesotho', 'LS', 'LSO', 'LES', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('120', 'Liberia', 'LR', 'LBR', 'LIB', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('121', 'Libyan Arab Jamahiriya', 'LY', 'LBY', 'LBY', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('122', 'Liechtenstein', 'LI', 'LIE', 'LIE', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('123', 'Lithuania', 'LT', 'LTU', 'LIT', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('124', 'Luxembourg', 'LU', 'LUX', 'LUX', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('125', 'Macau', 'MO', 'MAC', 'MAC', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('126', 'Macedonia, The Former Yugoslav Republic of', 'MK', 'MKD', 'F.Y', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('127', 'Madagascar', 'MG', 'MDG', 'MAD', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('128', 'Malawi', 'MW', 'MWI', 'MLW', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('129', 'Malaysia', 'MY', 'MYS', 'MLS', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('130', 'Maldives', 'MV', 'MDV', 'MAL', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('131', 'Mali', 'ML', 'MLI', 'MLI', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('132', 'Malta', 'MT', 'MLT', 'MLT', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('133', 'Marshall Islands', 'MH', 'MHL', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('134', 'Martinique', 'MQ', 'MTQ', 'MAR', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('135', 'Mauritania', 'MR', 'MRT', 'MRT', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('136', 'Mauritius', 'MU', 'MUS', 'MAU', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('137', 'Mayotte', 'YT', 'MYT', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('138', 'Mexico', 'MX', 'MEX', 'MEX', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('139', 'Micronesia, Federated States of', 'FM', 'FSM', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('140', 'Moldova, Republic of', 'MD', 'MDA', 'MOL', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('141', 'Monaco', 'MC', 'MCO', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('142', 'Mongolia', 'MN', 'MNG', 'MON', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('143', 'Montserrat', 'MS', 'MSR', 'MTT', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('144', 'Morocco', 'MA', 'MAR', 'MOR', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('145', 'Mozambique', 'MZ', 'MOZ', 'MOZ', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('146', 'Myanmar', 'MM', 'MMR', 'MYA', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('147', 'Namibia', 'NA', 'NAM', 'NAM', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('148', 'Nauru', 'NR', 'NRU', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('149', 'Nepal', 'NP', 'NPL', 'NEP', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('150', 'Netherlands', 'NL', 'NLD', 'NED', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('151', 'Netherlands Antilles', 'AN', 'ANT', 'NET', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('152', 'New Caledonia', 'NC', 'NCL', 'CDN', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('153', 'New Zealand', 'NZ', 'NZL', 'NEW', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('154', 'Nicaragua', 'NI', 'NIC', 'NIC', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('155', 'Niger', 'NE', 'NER', 'NIG', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('156', 'Nigeria', 'NG', 'NGA', 'NGR', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('157', 'Niue', 'NU', 'NIU', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('158', 'Norfolk Island', 'NF', 'NFK', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('159', 'Northern Mariana Islands', 'MP', 'MNP', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('160', 'Norway', 'NO', 'NOR', 'NWY', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('161', 'Oman', 'OM', 'OMN', 'OMA', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('162', 'Pakistan', 'PK', 'PAK', 'PAK', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('163', 'Palau', 'PW', 'PLW', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('164', 'Panama', 'PA', 'PAN', 'PAN', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('165', 'Papua New Guinea', 'PG', 'PNG', 'PAP', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('166', 'Paraguay', 'PY', 'PRY', 'PAR', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('167', 'Peru', 'PE', 'PER', 'PER', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('168', 'Philippines', 'PH', 'PHL', 'PHI', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('169', 'Pitcairn', 'PN', 'PCN', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('170', 'Poland', 'PL', 'POL', 'POL', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('171', 'Portugal', 'PT', 'PRT', 'POR', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('172', 'Puerto Rico', 'PR', 'PRI', 'PUE', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('173', 'Qatar', 'QA', 'QAT', 'QAT', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('174', 'Reunion', 'RE', 'REU', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('175', 'Romania', 'RO', 'ROM', 'ROM', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('176', 'Russian Federation', 'RU', 'RUS', 'RUS', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('177', 'Rwanda', 'RW', 'RWA', 'RWA', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('178', 'Saint Kitts and Nevis', 'KN', 'KNA', 'SKN', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('179', 'Saint Lucia', 'LC', 'LCA', 'SLU', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('180', 'Saint Vincent and the Grenadines', 'VC', 'VCT', 'ST.', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('181', 'Samoa', 'WS', 'WSM', 'WES', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('182', 'San Marino', 'SM', 'SMR', 'SAN', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('183', 'Sao Tome and Principe', 'ST', 'STP', 'SAO', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('184', 'Saudi Arabia', 'SA', 'SAU', 'SAU', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('185', 'Senegal', 'SN', 'SEN', 'SEN', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('186', 'Seychelles', 'SC', 'SYC', 'SEY', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('187', 'Sierra Leone', 'SL', 'SLE', 'SIE', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('188', 'Singapore', 'SG', 'SGP', 'SIN', '4');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('189', 'Slovakia (Slovak Republic)', 'SK', 'SVK', 'SLO', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('190', 'Slovenia', 'SI', 'SVN', 'SLV', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('191', 'Solomon Islands', 'SB', 'SLB', 'SOL', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('192', 'Somalia', 'SO', 'SOM', 'SOM', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('193', 'South Africa', 'ZA', 'ZAF', 'SOU', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('194', 'South Georgia and the South Sandwich Islands', 'GS', 'SGS', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('195', 'Spain', 'ES', 'ESP', 'SPA', '3');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('196', 'Sri Lanka', 'LK', 'LKA', 'SRI', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('197', 'St. Helena', 'SH', 'SHN', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('198', 'St. Pierre and Miquelon', 'PM', 'SPM', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('199', 'Sudan', 'SD', 'SDN', 'SUD', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('200', 'Suriname', 'SR', 'SUR', 'SUR', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('201', 'Svalbard and Jan Mayen Islands', 'SJ', 'SJM', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('202', 'Swaziland', 'SZ', 'SWZ', 'SWA', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('203', 'Sweden', 'SE', 'SWE', 'SWE', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('204', 'Switzerland', 'CH', 'CHE', 'ZWI', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('205', 'Syrian Arab Republic', 'SY', 'SYR', 'SYR', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('206', 'Taiwan', 'TW', 'TWN', 'TWN', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('207', 'Tajikistan', 'TJ', 'TJK', 'TAJ', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('208', 'Tanzania, United Republic of', 'TZ', 'TZA', 'TAN', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('209', 'Thailand', 'TH', 'THA', 'THA', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('210', 'Togo', 'TG', 'TGO', 'TOG', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('211', 'Tokelau', 'TK', 'TKL', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('212', 'Tonga', 'TO', 'TON', 'TON', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('213', 'Trinidad and Tobago', 'TT', 'TTO', 'TRI', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('214', 'Tunisia', 'TN', 'TUN', 'TUN', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('215', 'Turkey', 'TR', 'TUR', 'TUR', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('216', 'Turkmenistan', 'TM', 'TKM', 'TKM', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('217', 'Turks and Caicos Islands', 'TC', 'TCA', 'TCI', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('218', 'Tuvalu', 'TV', 'TUV', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('219', 'Uganda', 'UG', 'UGA', 'UGA', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('220', 'Ukraine', 'UA', 'UKR', 'UKR', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('221', 'United Arab Emirates', 'AE', 'ARE', 'UAE', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('222', 'United Kingdom', 'GB', 'GBR', 'GBR', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('223', 'United States', 'US', 'USA', 'UNI', '2');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('224', 'United States Minor Outlying Islands', 'UM', 'UMI', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('225', 'Uruguay', 'UY', 'URY', 'URU', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('226', 'Uzbekistan', 'UZ', 'UZB', 'UZB', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('227', 'Vanuatu', 'VU', 'VUT', 'VAN', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('228', 'Vatican City State (Holy See)', 'VA', 'VAT', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('229', 'Venezuela', 'VE', 'VEN', 'VEN', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('230', 'Viet Nam', 'VN', 'VNM', 'VIE', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('231', 'Virgin Islands (British)', 'VG', 'VGB', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('232', 'Virgin Islands (U.S.)', 'VI', 'VIR', 'US_', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('233', 'Wallis and Futuna Islands', 'WF', 'WLF', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('234', 'Western Sahara', 'EH', 'ESH', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('235', 'Yemen', 'YE', 'YEM', 'YEM', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('236', 'Yugoslavia', 'YU', 'YUG', 'YUG', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('237', 'Zaire', 'ZR', 'ZAR', '', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('238', 'Zambia', 'ZM', 'ZMB', 'ZAM', '1');
insert into osc_countries (countries_id, countries_name, countries_iso_code_2, countries_iso_code_3, countries_moneybookers, address_format_id) values ('239', 'Zimbabwe', 'ZW', 'ZWE', 'ZIM', '1');

